server:
  servlet:
    # 项目访问路径
    context-path: /WeChatMiniProgram

spring:
  profiles:
    # 指定配置环境
    active: dev

# WeChatMiniProgram项目配置
wmp:
  # 名称
  name: WeChatMiniProgram
  # 版本
  version: 1.0
  # 项目创建时间
  createTime: 2024-7-22
